---
title: 'Chapther 4: Introduction to R, Rstudio and ggplot'
author: "Haydeé Peruyero"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introducción

```{r}
library(ALDEx2)

#installed.packages()[1:5,] # que paquetes estan instalados

#Verificar si se cargó el paquete
#a<-installed.packages()
#packages<-a[,1]
#is.element("ALDEx2",packages) # está este paquete en el elemento 'packages´

#getwd() #para ver en que directorio estamos (path)

#setwd("/home/betterlab/GIT/Intro_R") #crea un directorio especifico para trabajar,si queremos cambiar de getwd()
#getwd()
```

```{r}
data <- read.csv("D:/Users/hayde/Documents/R_sites/Analisis_estadistico_de_datos_de_Microbioma_con_R/data/hsb2demo.csv")

boxplot(write~female,data,main="High School Students Data",xlab="Gender",ylab="writing scoreby gender")
```

```{r}
tab1 <- read.table("D:/Users/hayde/Documents/R_sites/Analisis_estadistico_de_datos_de_Microbioma_con_R/data/hsb2demo.csv",header=TRUE,row.names=1,sep="\t")
tab1
```
```{r}
raw <-"https://raw.githubusercontent.com/swcarpentry/r-novice-gapminder/gh-pages/_episodes_rmd/data/gapminder_data.csv"
tab2 <- read.table(raw,sep='\t',header=TRUE,row.names=1,check.names=FALSE,stringsAsFactors=FALSE)
tab2
```
```{r}
tab3 <- read.delim("D:/Users/hayde/Documents/R_sites/Analisis_estadistico_de_datos_de_Microbioma_con_R/data/hsb2demo.csv", header=T, row.names=1)
tab3
```


```{r}
tab4 <- read.csv('D:/Users/hayde/Documents/R_sites/Analisis_estadistico_de_datos_de_Microbioma_con_R/data/hsb2demo.csv',head=T,row.names=1,sep=',',dec='.')
tab5 <- read.csv2('D:/Users/hayde/Documents/R_sites/Analisis_estadistico_de_datos_de_Microbioma_con_R/data/hsb2demo.csv',head=T,row.names=1,sep =';',dec=',')
```



```{r}
#install.packages("gdata") # este paquete nos ayuda con la lectura de .xls directamente.
library(gdata)
```


```{r}
#tab6 <- read.xls(“table.xlsx”,sheet=1,header=TRUE) 
#tab7 <- read.xls(“table.xlsx”,sheet=1,perl=“C:/Perl64/bin/perl.exe”)
```


```{r}
#install.packages ("XLConnect") # este paquete sirve para manipular archivos de excel en windows.
#library (XLConnect)
```

```{r}
data()
attach(iris)
head(iris)
```


```{r}
#crear data frame usando indices de columna
df <- iris[,c(1,2,3)]
head(df)
```


```{r}
# crear data frame usando indices de columna con secuencias
df <- iris[,c(1:2,4:5)]
head(df)
```

```{r}
# crear data frame usando subset() e indices de columnas
df<- subset(iris, select=c(1,2, 4:5))
head(df)
```

```{r}
# crear data frame usando subset() e nombres de columnas
df <- subset(iris, select=c("Sepal.Width","Petal.Length", "Petal.Width"))
head(df)
```

```{r}
# crear data frame por seleccion de nombres de columnas
df <- iris[,c("Sepal.Width","Petal.Length","Petal.Width")]
head(df)
```

```{r}
# crear data frame usando dataframe()
df <- data.frame(iris$Sepal.Width,iris$Petal.Length,iris$Petal.Width)
head(df)
```


```{r}
# crear data frame usando c() manualmente
Sepal.Width = c(3.5, 3.0, 3.2, 3.1,3.6,3.9)
Petal.Length = c(1.4,1.4,1.3,1.5,1.4,1.7)
Petal.Width = c(0.2,0.2,0.2,0.2,0.2,0.4)
df = data.frame(Sepal.Width,Petal.Length,Petal.Width)
df
```


```{r}
head(iris) #nos muestra una pequeña parte de los datos
```

```{r}
attributes(iris) #imprime los nombres de las filas y columnas,y la clase de los datos
```

```{r}
class(iris)
dim(iris)
nrow(iris)
ncol(iris)
length(iris[,"Species"])
colnames(iris)
rownames(iris)
#print(iris)
```

```{r}
Species <- iris[,"Species"]
Species
```
```{r}
iris[1,3] #se puede acceder por posicion

iris["1","Petal.Length"] #o por nombre de fila y columna

tab = read.csv("D:/Users/hayde/Documents/R_sites/Analisis_estadistico_de_datos_de_Microbioma_con_R/data/hsb2demo.csv",row.names=1,check.names=FALSE)
sum(tab == 0) # podemos contar cuantos elementos del archivo son cero
sum(tab != 0) #y cuantos son diferentes de cero
```


```{r}
# layout(matrix, widths=w; heights=h)
# diseño(matriz, ancho=w; alto=h)
ng <- layout(matrix(c(1,3,2,3),2,2, byrow=TRUE), widths=c(5,2),height=c(3,4))
layout.show(ng)
```


```{r}
summary(iris)
```
```{r}
iris_1 <- (iris[,-5])
head(apply(iris_1, 1, mean))
```
```{r}
apply(iris_1, 1, mean)
```
```{r}
apply(iris_1, 2, mean,na.rm = TRUE)
```

```{r}
#apply(DataFrame, dimension = Son identificadas con números, 1 son renglones y 2 son colummnas,funcion que 
tab_perc <- apply(tab, 2, function(x){x/sum(x)})
tab_perc
```


```{r}
tab_perc <- apply(tab[,1:ncol(tab)-1], 2, function(x){x/sum(x)})
tab_p1 <- tab[apply(tab_perc, 1, max)>0.01,]
tab_p2 <- tab[apply(tab_perc, 1, min)>0.01,]
head(tab_p2)
```



```{r}
iris_t <-t(iris) #toma la traspuesta del dataframe
iris_t[1:5,1:6]
```



```{r}
# ordenar el dataframe
iris_2 <- (iris[,-c(3:5)])
sorted <- sort(iris_2$Sepal.Length)
#sort() y order(), ordenan(Sepal.Length) de forma ascendente
ordered <- order(iris_2$Sepal.Length)
new_iris<- data.frame(iris_2,sorted,ordered)
head(new_iris)
```

```{r}
rev_iris <- rev(sort(iris_2$Sepal.Length))
# ordena de forma descendente
head(rev_iris)
```

```{r}
head(iris[order(Sepal.Length),])
```

```{r}
head(iris[order(iris[,'Sepal.Length']),])
```


## Intro a dplyr

```{r}
#instaler y cargar el paquete
#install.packages("dplyr")
library("dplyr")
```

```{r}
tab <- read.csv('D:/Users/hayde/Documents/R_sites/Analisis_estadistico_de_datos_de_Microbioma_con_R/data/hsb2demo.csv')
head(tab)
```

```{r}
tab %>% 
  select(id,write) %>% 
  head
```

```{r}
head(select(tab, id, read, write, math))
```

```{r}
head(select(tab, read:socst))
```

```{r}
head(select(tab, - female))
```


```{r}
head(select(tab, - (female:prog )))
```

```{r}
head(select(tab, starts_with("s")))
```


```{r}
#filtra las fila de estudiantes con puntaje de lectura mayor o igual a 70.
filter(tab, read >= 70)
```


```{r}
#Filtra las filas de estudiantes con un puntaje de lectura y matematica mayor o igual a 70
filter(tab, read >= 70, math >= 70)
```

```{r}
#ordena por read y luego por write
head(arrange(tab, read, write))
```

```{r}
#Usamos desc() para odenar una columna en orden decreciente
head(arrange(tab, desc(read)))
```

```{r}
head(arrange(tab, desc(female),read)) #ejemplo
```

```{r}
tab %>% arrange(female) %>% head
```

```{r}
#Primero selecciona las columnas id, gender, read de tab, luego ordena las filas por gender y luego por 
tab%>%
  select(id, female, read) %>% 
  arrange(female, read) %>% 
  head
```


```{r}
# Filtramos las filas por 'read' con un puntaje mayor o igual a 70
tab %>% select(id, female, read) %>% arrange(female, read) %>% filter(read >= 70)
```

```{r}
#realizamos los mismos pasos anteriores, pero con orden descendente
tab %>% select(id, female, read) %>% arrange(female, desc(read)) %>% filter(read >= 70)
```

```{r}
#Calculamos los puntajes promedio de lectura y escritura
head(mutate(tab, avg_read = sum(read)/n()))
```


```{r}
tab %>% mutate(avg_read = sum(read/n())) %>% head
```

```{r}
#contrae un dataframe en una sola fila.
summarise(tab, avg_read = mean(read, na.rm = TRUE))
```

```{r}
tab %>% summarise(avg_read = mean(read),min_read = min(read),max_read = max(read),n = n())
```

```{r}
#primero agruparemos por genero y luego muestra las estadisticas obtenidas (media, minimo y maximo)
by_gender <- group_by(tab, female)
read_by_gender <- summarise(by_gender,
n = n(),
avg_read = mean(read, na.rm = TRUE),
min_read = min(read,na.rm = TRUE),
max_read = max(read,na.rm = TRUE))
read_by_gender
```



